apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-workflow

on:
  push:
    branches:
      - "**"

jobs:
  build:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "hello world 5"
